sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7.3

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "nageom1123@naver.com"
  - git config --global user.name "nageom"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "oXu50MjpHlPIbPIdivhwwzNPQ75P6YOI42dX4sWw3k/7MptWNhpzBRaFnTyJog/j6W9CuTcuRipz2Meq5qx8/3DIfWpXi/T+BUjnKoqb0133D6dqmVUeV1T/R7qB3qCmttWZkaUvIwmLW0LWVLakeS50cjWiBwGJcmll67bwV+KQ86oqai2tEVZHrNvPLMjKFtnFoqdMCGElFPGONfdcIZG2yFz/nF77
            nentMq/Ke5haf5/Giu3G59YsLkc7XV9LSMtL1WpHSbIl2iO3ab9K6AXhln1pymk6JD2FTSKpfQ3UMne2VTbWPZrwHwhHt2cPBKRooy5DIQviUz6uab+6zs3AVk486edkq3nvkdliKxAulayml147+DsKHXtKgAAi5KxrBnrbTRGxWLGZV9SaZNH3dYHqs3fM83/RyvYHVAMHWImI0/P6ns5TXORX4gwtF8gO0XZQjj5
            S9jFLwLfZjMYMhliOSFq5AT4uAp/jj+jf99SJrl4pif6B3Cx1pFHLhHjdapWrFv0yzdT8B0vzoU2MhsTBvkY4y8Lyx9Kp4CTzdRwXLHX4HXX249lVfove75Y49d1iiKD48DvpYo1e/D2zVnmR+DmzqDKUstWPHuyI7AwHp1fPBQEpXU1tV7nwuGUbDXE14Qm9aZWZVQ79bu/dCLFQqWyE5BI0CgTbdGo="
branches:
  only:
    - master